{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ template "elasticsearch.name" .}}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: cluster-view-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: {{ template "elasticsearch.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- range .Values.accessList }}
- kind: {{ .kind }}
  name: {{ .name }}
  namespace: {{ .namespace }}
{{- end }}
{{- end -}}