apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: default
  labels:
    this: test
  annotations:
    this-test: testing
spec:
  externalName: proxy-test
  sessionAffinity: None
  type: ExternalName