apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tr1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tr1
subjects:
- kind: User
  name: testuser
- kind: ServiceAccount
  name: default